<?php

$storeID = Mage::helper("przelewy")->getStoreID();

$productPrice = Mage::registry('current_product')->getFinalPrice();

if ((int)Mage::getStoreConfig('przelewytab1/paysettings/raty',
        $storeID) == 2 && $productPrice >= Dialcom_Przelewy_Model_Payment_Przelewy::getMinRatyAmount()
    && Mage::app()->getStore()->getCurrentCurrencyCode() == "PLN"
) {

    $jsonString = Dialcom_Przelewy_Model_Payment_Przelewy::requestGet('https://secure.przelewy24.pl/kalkulator_raty.php?ammount=' . (int)($productPrice * 100) . '&format=json');

    $json = json_decode($jsonString);
    ?>

    <script type="text/javascript">
        $j(document).ready(function () {
            $j('.price-info:first').append('<div class="price-box"><a class="price-installment" ' +
                'target="_blank" href="https://secure.przelewy24.pl/kalkulator_raty/index.html?ammount=<?php echo floatval($productPrice); ?>">' +
                '<img src="<?php echo $this->getSkinUrl('images/przelewy/logo_129.gif '); ?>"> <?php echo (int)$json->ilosc_rat; ?> rat x <?php echo (int)$json->rata; ?> zł </a>' +
                '<a class="price-installment" target="_blank" href="http://www.mbank.net.pl/mraty_1/index.html?kwota=<?php echo floatval($productPrice); ?>"> ' +
                '<img src="<?php echo $this->getSkinUrl('images/przelewy/logo_136.gif '); ?>"></a></div>'
            );

        });
    </script>

<?php } ?>